[instance]
problem_instance = "/fjsp/1_Brandimarte/Mk01.fjs"

[solver]
time_limit = 3600       # time limit for the OR-tools CP-SAT solver, in seconds
model = "fjsp"          # model to use, either 'jsp', 'fsp', fjsp' or 'fjsp_sdst'

[output]
show_gantt = true       # draw ganttchart of found solution
save_gantt = true       # save ganttchart to file
save_results = true     # save results to file
exp_name = ""           # name of the experiment, used for saving results.
                        # If empty (""), the name of the problem instance is used
folder = ""             # folder to save results, used for saving results.
                        # If empty (""), the results are saved to the current working directory.

